apiVersion: v1
kind: Pod
metadata:
  name: bpftrace-test
spec:
  shareProcessNamespace: true   # allow containers to see each other's processes
  initContainers:
  - name: bpftrace
    image: ghcr.io/amirhnajafiz/flap:v0.0.0-beta-6
    securityContext:
      privileged: true                # or at least add CAP_SYS_PTRACE
      capabilities:
        add: ["SYS_PTRACE"]
    command: ["sleep", "infinity"]
  containers:
  - name: nginx
    image: nginx:latest


