apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: bpftrace
  ports:
    - name: http-web-svc
      port: 80
      targetPort: http-web-svc
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: bpftrace-test
  labels: 
    app: bpftrace
spec:
  shareProcessNamespace: true   # allow containers to see each other's processes
  initContainers:
    - name: bpftrace
      image: ghcr.io/amirhnajafiz/flap:v0.0.0-beta-8
      restartPolicy: Always
      securityContext:
        privileged: true                # or at least add CAP_SYS_PTRACE
        capabilities:
          add: ["SYS_PTRACE"]
      volumeMounts:
      - name: debug
        mountPath: /sys/kernel/debug
      - name: output
        mountPath: /var/log/bpftrace
      command: ["sh", "-c"]
      args:
        - |
          ts=$(date +"%Y-%m-%d_%H-%M-%S");
          outfile="/var/log/bpftrace/${ts}.out";
          ./trace.sh -n "nginx" -o "$outfile"
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - name: http-web-svc
        containerPort: 80
  volumes:
    - name: debug
      hostPath:
        path: /sys/kernel/debug
    - name: output
      hostPath:
        path: /var/log/bpftrace
