apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flap-daemon
  namespace: flap
  labels:
    app: flag-daemon
    type: daemonset
spec:
  selector:
    matchLabels:
      app: flap
      type: daemon
  template:
    metadata:
      labels:
        app: flap
        type: daemon
    spec:
      hostPID: true
      containers:
      - name: tracer
        image: ghcr.io/amirhnajafiz/flap:v0.0.0-beta-5
        command: ["/usr/local/app/trace.sh"]
        args:
          - >
            -h
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "512Mi"
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /proc
      restartPolicy: Always
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc

