name: Build and push beta versions Docker images to a container registry

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set image tag value
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RE_GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        env:
          TAG: "${{ steps.vars.outputs.tag }}-dev"
        with:
          push: true
          files: "build/docker-bake.json"
